### ISSUE TITLE
Missing certificate and/or requirement file?

### ISSUE THREAD

**Issue by jan-brabec** [Deep-MI/LaPy#20]
I tried to install Lapy under Ubuntu 22.04 that is installed under WSL2 (Windows 10). I am interested in FastSurfer and this is one of the prerequisites for FastSurfer.

After running command "python3 -m pip install lapy" error occurred:

```Could not fetch URL https://pypi.org/simple/lapy/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/lapy/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)'))) - skipping```

I also tried running command "pip install --trusted-host pypi.org lapy" instead.

However, error occurred: 

```ERROR: Could not find a version that satisfies the requirement lapy (from versions: none)```
```ERROR: No matching distribution found for lapy```

**Comment by mscheltienne** [comment]
Hello,

I am running on all 3 OS without an issue. 
The error hints to a `pip` related error and not something specific to `lapy`. I think you are getting the same error if you try to install other packages with `pip`.
From a quick search with `pip could not fetch url ssl certificate`:
- https://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi
- https://stackoverflow.com/questions/49943410/pip-ssl-error-on-windows
- https://jhooq.com/pip-install-connection-error/

Mathieu
