### ISSUE TITLE
Can you provide Laplace-Beltrami operator on hexahedron meshes？

### ISSUE THREAD

**Issue by LiChengChen666** [Deep-MI/LaPy#23]
## Question/Support Request

...

## Screenshots

...

## Environment
 - LaPy Version: ...
 - OS: ...
 - CPU: ...

**Comment by m-reuter** [comment]
Should be straight forward, we can put it on the Todo list. If anyone starts working on it, they can report here.

**Comment by m-reuter** [comment]
By the way often hex meshes are not pure, but a mix of hexahedra and tetrahedra. I think the best approach is to split each hexahedron into 5 tetrahedra as a pre-processing step?

**Comment by m-reuter** [comment]
closing this, as no one can work on it. And the interim solution is to reduce to tet-mesh. We can reopen as soon as anyone wants to work on it.
