### ISSUE TITLE
PLY file loader

### ISSUE THREAD

**Issue by bearinsuke** [Deep-MI/LaPy#3]
Hi,

Thank you for contributing very cool stuff! But I still have a little question: how to load point cloud files such as ply or obj? Plus, for some simple geometry that only contains point geometry, can the lb operator still handle that kind of file?

Thanks

**Comment by m-reuter** [comment]
Hi @bearinsuke currently only VTK OFF GMSH and FreeSurfer Surface files are supported. Should be easy to add ply or obj support, probably there are already python packages to load those files. All you need is the list of 3D points and triangles as 3 indices into that list (starting with 0). Or you can use any converter to one of the supported inputs. 

Also this implementation cannot handle point clouds, you would need to create a geometry ( triangle or tetrahedral meshes) first.

**Comment by bearinsuke** [comment]
Hi @m-reuter, thanks for your comments. Here is a further question I'd like to ask: since the information contained in the triangle is the indices of vertices, is it possible to use edge information so that LBO may handle simple geometry such as a 2d ring shape or something?
Thanks

**Comment by m-reuter** [comment]
It uses angles at vertices. It can only work on triangle meshes (or the 3d version on tet-meshes). It would be easy to implement a more simple graph laplacian at some point, that would work on any graph (basically vertices and edges).

**Comment by bearinsuke** [comment]
Thanks for your help!
