### ISSUE TITLE
Orthonormal eigenvectors

### ISSUE THREAD

**Issue by sina-mansour** [Deep-MI/LaPy#39]
## Question/Support Request

Hi,

I'm using Lapy to generate Laplace Beltrami Operators of a surface mesh. 

In my experience, the eigenvectors generated by `lapy.solver.Solver(mesh).eigs` are neither orthogonal, nor unit norm vectors. I wanted to check if this is expected behavior? Given that the mesh structure is a symmetric matrix, should the eigenvectors be orthonormal?

## Screenshots

Here's a heatmap of the dot product of pairs of eigenvectors for the first 20 eigenvectors:

![image](https://github.com/Deep-MI/LaPy/assets/16105138/7926a977-e03b-4be9-8be4-42a3b6290046)

And here's what other tools (like numpy.linalg.eigs) would generate. Note that for orthonormal eigenvectors, the dot products on the diagonal are all one (because of the unit norm) and off-diagonal values are all zero (because of orthogonality). I think the Lapy eigenvectors should have ideally been orthonormal too:

![image](https://github.com/Deep-MI/LaPy/assets/16105138/7aa08158-b651-4466-82b9-2bfe43b0a7ac)

## Environment
 - LaPy Version: Latest (as of June 2023)
 - OS: Ubuntu

**Comment by m-reuter** [comment]
Hi, 
this is a generalised eigenvalue problem A x=lambda B x (see https://en.wikipedia.org/wiki/Eigendecomposition_of_a_matrix#Generalized_eigenvalue_problem ) and the eigenvectors will be B-orthonormal: x1^t B x2 = 0 ...
