### ISSUE TITLE
Solving the Helmholtz equation using the Laplacian as a Linear Operator

### ISSUE THREAD

**Issue by VictorBarnes** [Deep-MI/LaPy#45]
## Question/Support Request

I’m using two methods to compute the eigenmodes of a surface mesh. For the first method I use `lapy.Solver.eigs` where the Laplacian is defined as $B^{-1} A$. For the second method I define the Laplacian as $-\nabla \cdot \nabla f \coloneqq -\text{div}(\text{grad} f)$ using `lapy.diffgeo.compute_divergence` and `lapy.diffgeo.compute_gradient`. However, these two methods give different results. 
## Screenshots and code snippets

I tested this by modifying the `Test_TriaMesh_Geodesics.ipynb` notebook. I'm using the 3rd non-constant eigenmode as a test case because it clearly shows the discrepancy in results between the two methods.

For the first method I solve the first 10 eigenmodes using `lapy.Solver.eigs` and plot the 3rd non-constant eigenmode.
```python
from lapy import TriaMesh, Solver
from lapy.plot import plot_tria_mesh

T = TriaMesh.read_off("../data/square-mesh.off")
fem = Solver(T, lump=True)
evals, emodes = fem.eigs(k=10)

plot_tria_mesh(T, emodes[:, 3], plot_edges=True)
```

![image](https://github.com/Deep-MI/LaPy/assets/79833032/039eb8ff-3259-4f2f-a4d4-b1acc0087219)

For the second method I solve the first 10 eigenmodes by defining the Laplacian as $-\nabla \cdot \nabla f$ . I do this by combining `compute_gradient` and `compute_divergence` into a function and defining it as a `scipy` linear operator.

```python
from scipy.sparse.linalg import LinearOperator
from lapy.diffgeo import compute_gradient, compute_divergence

class DivGradOperator(LinearOperator):
    def __init__(self, geom, dtype="float32"):
        self.geom = geom
        self.shape = (geom.v.shape[0], geom.v.shape[0])
        self.dtype = np.dtype(dtype)
    def _matvec(self, vfunc):
        """Compute the effect of the operator on the input vector vfunc."""
        return -compute_divergence(self.geom, compute_gradient(self.geom, vfunc))

divgrad_op = DivGradOperator(T, dtype="float32")
```

I then feed the linear operator into `scipy.sparse.linalg.eigsh` and plot the 3rd non-constant eigenmode.

```python
evals, emodes = eigsh(divgrad_op, 10, sigma=-0.01)
plot_tria_mesh(T, emodes[:, 3], plot_edges=True)
```

![image](https://github.com/Deep-MI/LaPy/assets/79833032/156c1d7f-c0c2-4861-ae20-4da34b08c09d)

Is my implementation of the second method wrong? Or is it not possible to use the `compute_gradient` and `compute_divergence` functions to solve the Helmholtz equation? Or is there some other problem here?

Thanks in advance!

## Environment
 - LaPy Version: 1.0.1
 - OS: Linux

**Comment by m-reuter** [comment]
Hi, take a look at our tutorial, specifically here: https://deep-mi.org/LaPy/dev/tutorials/examples/Test_TriaMesh_Geodesics.html  box [9]. You probably need to multiply by B inverse to get back from the integrated divergence to the function on the vertices. See also https://github.com/Deep-MI/LaPy/blob/1d915113bc54ca6f9f03ce94926398fd3683ced2/lapy/diffgeo.py#L227

**Comment by VictorBarnes** [comment]
Thanks for your quick reply! I had tried that as well but the discrepancy still remained. 

However, using the matrix multiplication operator `@` (instead of `*`) and using `scipy.sparse.linalg.eigs` (instead of `scipy.sparse.linalg.eigs`) seems to solve the issue. I believe we need to use `eigs` because `eigsh` assumes the input matrix is symmetric (which isn't the case when using the `DivGradOperator` method).

```python
class DivGradOperator(LinearOperator):
    def __init__(self, geom, Binv, dtype="float32"):
        self.geom = geom
        self.Binv = Binv
        self.shape = (geom.v.shape[0], geom.v.shape[0])
        self.dtype = np.dtype(dtype)
    def _matvec(self, vfunc):
        """Compute the effect of the operator on the input vector vfunc."""
        return self.Binv @ -compute_divergence(self.geom, compute_gradient(self.geom, vfunc))

B = fem.mass
Binv = B.copy()
Binv.data **= -1
divgrad_op = DivGradOperator(T, Binv, dtype="float32")

evals, emodes = eigs(divgrad_op, 10, sigma=-0.01)

plot_tria_mesh(T, emodes.real[:, 3], plot_edges=True)
```

![image](https://github.com/Deep-MI/LaPy/assets/79833032/e225ae5c-15b2-4d25-8d3e-d163bdcf495a)

It still does take a while longer to run (~3 mins instead of ~3 secs for the first 10 modes). I modified `compute_gradient` and `compute_divergence` using `numexpr` as suggested in the code. This slightly improved the runtime. Do you have any other suggestions to speed things up?

**Comment by m-reuter** [comment]
Yes, of course it is a matrix multiplication. We need to re-check our tutorial, I think it is not correct there. Thanks for pointing that out. 

And why do you use the gradient and divergence? You could simply use the solver and get both the mass matrix (you do that already) and the stiffness matrix $A$ and compute $B^-1 A$ directly (inversion of $B$ is generally expensive, but not in your case, as you lump the mass matrix, so it is a diagonal matrix where you can simply invert the diagonal elements). 

About speed, the question is why are you doing it this way? There is a reason why we solve the generalised symmetric problem $A x = \lambda B x$ instead of the non symmetric $B^-1 A x = \lambda x$ . Of course destroying the symmetry when reducing it to a regular eigenvalue problem is a bad idea both with respect to speed and numerical issues.

**Comment by VictorBarnes** [comment]
I need to calculate the divergence of the gradient because my goal is to solve heterogeneous Helmholtz equation $-\nabla (c_s(x,y) \cdot \nabla) f = \lambda f$ where $c_s$ describes the heterogeneity of the surface (e.g. variation in density) at each vertex.

**Comment by m-reuter** [comment]
That is a simplified setting compared to our anisotropic operator, where the $c$ is basically a 2x2 matrix (with respect to a basis of tangent vectors, in our case the principal curvature directions). So by setting both diagonal elements of that matrix to $c_s(x,y)$ you should be able to achieve the same thing directly. See https://github.com/Deep-MI/LaPy/blob/1d915113bc54ca6f9f03ce94926398fd3683ced2/lapy/solver.py#L180 for the implementation of the anisotropic operator (in your case it would be spatially varying, but isotropic).

**Comment by VictorBarnes** [comment]
Thanks, that seems more reasonable.

I added an argument called `hetero` (with length n_triangles) into the `Solver` class and then multiply `aniso_mat` by `hetero` (note: I also set `aniso=(0, 0)` since I want isotropic diffusion). In this screenshot only lines 94 and 95 have been added in.
![image](https://github.com/Deep-MI/LaPy/assets/79833032/8d46f466-527e-49ab-a91f-fbbda27cdeda)

I've tried a few test cases and it seems to be running well. Thanks so much for your help!

**Comment by m-reuter** [comment]
Happy to hear this works for you. Maybe at some point we will add this type of functionality to the code. I have been thinking already to do the whole thing differently and allow passing the matrix entries directly instead of doing the curvature stuff in the solver. Need to think about how to best do this so that it is user friendly, flexible, and clean.
