### ISSUE TITLE
Discrepancy in Sign Convention for Curvature in `TriaMesh.curvature()`

### ISSUE THREAD

**Issue by VictorBarnes** [Deep-MI/LaPy#52]
## Description
I am encountering a discrepancy in the sign convention for curvature in the `TriaMesh.curvature()` function. According to my understanding and the reference cited in the function (Alliez et al., 2003), convex curvature should be defined as positive and concave curvature as negative.

However, my testing indicates the opposite: convex curvature is being reported as negative and concave curvature as positive. I have verified that the triangle orientations are correct and that the triangle normals point outward. 

Here is a plot of the max curvature on the provided `icosahedron.off` file (the min and mean curvatures are also all negative):
![image](https://github.com/Deep-MI/LaPy/assets/79833032/266c22f5-a8c7-404e-9ebc-007e7981210d)

I am seeking clarification on the following:
- Why does the sign convention in `TriaMesh.curvature()` differ from the established convention?
- Are there any potential implications or limitations to using this alternative sign convention?

## Environment
 - LaPy Version: 1.0.1

**Comment by m-reuter** [comment]
Hmm, this is indeed strange and I don't remember why this convention was used. I will need to take a look, maybe we can flip the sign in a future release. 

I don't think there are any limitations of this convention.

**Comment by VictorBarnes** [comment]
Thanks, good to know. Removing the negative sign from line 675 in `tria_mesh.py` could be a good option for where to make the change.

**Comment by m-reuter** [comment]
OK.  If a curve curves away from the normal vector it is usually defined to have negative curvature. On a sphere with outward pointing normals, this is true for all directions and thus both principal curvatures are negative, as well as the mean curvature. Only the Gauss curvature is positive. 

This definition also agrees with the equation 
2 H = trace ( II * I^(-1) )  where the second fundamental form is usually negative for outward pointing normals. 

This wikipedia article also states that the mean curvature is "positive if the surface curves towards the normal", which would be true for the sphere only if normals pointed inwards:
https://en.wikipedia.org/wiki/Mean_curvature

So we will keep this convention unless there is a good reason to change it.
