### ISSUE TITLE
Heat Kernel Signature: No link to the curvature?

### ISSUE THREAD

**Issue by ldv1** [Deep-MI/LaPy#53]
Hi,

I use LaPy to compute the Heat Kernel Signature (HKS). However, I have hard times interpreting this HKS. For small t, the HKS at a point is directly related to the Gaussian curvature. But this is not what I can see.

Here is my code, and to illustrate my point I take the "duck" from Trimesh:

```
import sys
sys.path.append("./mesh-signatures")
import trimesh
import pyvista as pv
from lapy import TriaMesh
from lapy import Solver, heat
import numpy as np
import math

# load the trimesh duck model
tmesh = trimesh.load("./trimesh/models/duck.dae", force="mesh")

# convert to pyvista
mesh = pv.wrap(tmesh)

# make it a TriaMesh
trias = mesh.faces.reshape(-1, 4)[:, 1:]
points = mesh.points
points = points / 100. # rescale approx into [-1,1]
T = TriaMesh(points,trias)

# compute HKS
K = 300
fem = Solver(T)
evals, evecs = fem.eigs(k=K)
evals = evals.reshape(-1,1)
print(evals[:10])
evals[ evals < 0 ] = 0.
t_start = 4 * math.log(10) / evals[-1]
t_end = 4 * math.log(10) / evals[7]
time_scales = np.array(np.logspace(np.log(t_start), np.log(t_end), num=16)).reshape(1,-1)
hks = heat.diagonal(time_scales, list(range(len(points))), evecs, evals, K)

# plot duck colored by the first HKS entry
mesh.point_data.set_scalars(hks[:,0], "HKS0")
mesh.plot(scalars="HKS0", show_edges=True)
```

There is apparently a numerical issue and some eigenvalues are negative though they should be all greater or equal to 0. So I set the negative eigenvalues to 0. 

This is the plot the first component of the HKS:

![duck_hks0](https://github.com/Deep-MI/LaPy/assets/12841688/7f6daf81-e62f-4bcb-a54b-1a70efcf2d92)

And the second component of the HKS:

![duck_hks1](https://github.com/Deep-MI/LaPy/assets/12841688/8f07ad8c-dbbc-44ca-bd39-c5d4849c345e)

I can't see any link to the curvature.

My questions are: 1) why do we have a numerical issue here, and 2) why can't we relate the LaPy HKS to the curvature at the small time scales ?

Thanks for any help.

**Comment by m-reuter** [comment]
I think your mesh is broken. The shading does not look smooth. Please try this again with a manifold mesh with spherical topology. 

What is the Euler Characteristic of your mesh? Is it manifold? How far from zero is the smallest eigenvalue?

**Comment by ldv1** [comment]
I took the duck from the [Trimesh repo](https://github.com/mikedh/trimesh/tree/main/models).

Is watertight? False
Euler number: 5

The shading does not look smooth, but the color is coded according to the values of the first component of the HKS.

If I take the [torus](https://github.com/mikedh/trimesh/blob/main/models/torus.STL) I got:

is watertight? True
Euler number: 0
TriaMesh with regular Laplace-Beltrami
Solver: spsolve (LU decomposition) ...
Eigenvalues:
[[5.81305837e-15]
 [9.98818399e-01]
 [9.98818407e-01]
 [3.18660628e+00]
 [3.18660630e+00]
 [3.92009890e+00]
 [4.50241560e+00]
 [5.07640912e+00]
 [5.07640914e+00]
 [6.21071994e+00]]

HKS 0:

![torus0](https://github.com/Deep-MI/LaPy/assets/12841688/324104dc-2259-4a2b-a484-ec3f1de90b49)

HKS 1:

![torus1](https://github.com/Deep-MI/LaPy/assets/12841688/d74ef862-9948-4fab-aed1-cf84871f9000)

If the first HKS was proportional to the curvature, I would expect the constant stripes to be orthogonal to what we can see. So I do not get it.

**Comment by m-reuter** [comment]
OK, torus looks already much better. You can also try to refine the mesh more as there are not many triangles. 

But about the interpretation, not sure either. There could also still be a bug somewhere in the heat kernel diagonal. Maybe it would be good to try to replicate a result of the HKS paper. I think they used the dragon mesh.

**Comment by ldv1** [comment]
That's a good idea. I will see what I can do.

**Comment by ldv1** [comment]
It is possible to get the Stanford dragon from pyvista:

```
from pyvista import examples
mesh = examples.download_dragon()

```
however, I get
```
TriaMesh with regular Laplace-Beltrami
Solver: spsolve (LU decomposition) ...
Traceback (most recent call last):
  File "/home/laurent/test/test55.py", line 36, in <module>
    evals, evecs = fem.eigs(k=K)
                   ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lapy/solver.py", line 651, in eigs
    lu = splu(self.stiffness - sigma * self.mass)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py", line 433, in splu
    return _superlu.gstrf(N, A.nnz, A.data, indices, indptr,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Factor is exactly singular
```

There are other triangulated surfaces usually used to demonstrate the differences between various signatures, like a hand or Homer, but I cannot get my hands on them.

**Comment by ldv1** [comment]
I manged to get my hands onto the Standaford asian dragon, decimate it and fix it, and results seems to be ok.
The HKS at the smallest time scale looks like this, with high values only at the spikes:

![dragon_0_first_time](https://github.com/Deep-MI/LaPy/assets/12841688/533f6707-1654-4b13-9362-f9b0b1c28051)

At the greatest time scale, everything is uniform, as expected.
So, I will close this issue, nevertheless I have hard times interpreting the HKS for other surface meshes and relate it to the Gaussian curvature.

**Comment by m-reuter** [comment]
Thanks for the update. I think the Duck mesh was broken, the torus was very coarse and of course is very uniform and smooth. For the dragon, maybe if you use a different color scale (heat map, but with zero shifted to 0.003 or so) you would better see that the smallest values are in concave regions (negative gauss curvature) and the highest are in the convex areas (as can already be seen).
