### ISSUE TITLE
How to generate mesh with only nodes?

### ISSUE THREAD

**Issue by YuchiQiu** [Deep-MI/LaPy#54]
Very useful tool! 

I found TriaMesh and and TetMesh all require input of points and triangles/tetrahedral. Do you have recommended package to generate triangle or tetrahedral from points (nodes) only? 

Thank you.

**Comment by m-reuter** [comment]
It is quite difficult to generate a mesh from a point cloud, as there are many solutions. I think probably CGAL https://www.cgal.org could help. 
See also here: https://stackoverflow.com/questions/34887019/surface-mesh-from-point-cloud#:~:text=Right%20now%20there%20are%203,Scale%20space%20reconstruction
