### ISSUE TITLE
TriaMesh.orient_() trapped in an infinite loop

### ISSUE THREAD

**Issue by ldv1** [Deep-MI/LaPy#56]
Hi,

For a given triangulated surface mesh, `TriaMesh.orient_` is trapped in an infinite loop, more precisely at this point:

```
while len(v.data) < tdim:
                count = count + 1
                v = tmat * v
                v.data = np.sign(v.data)
```

This mesh has two disconnect components, but another mesh of mine has also two disconnected components and `orient_()` works fine.
Would you a clue what could cause this infinite loop?
Thanks for the help.

**Comment by m-reuter** [comment]
It was never designed to work on disconnected components, maybe try to separate them and run on each separately? 
I would need to take a closer look to figure out why, and how to fix it.

**Comment by ldv1** [comment]
Yes, I thought also about this option of working on the components independently, but if in the future LaPy could handle disconnected components, that would be great! So I will close this issue.
